import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

//style
import '@/style/globals.scss'
import Header from "@/component/header";
import LayoutComponent from "@/component/layoutComponent";

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <Header />
            <div>
                <LayoutComponent />
                {children}
            </div>
        </div>
    );
}